apiVersion: azure.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: az-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: azure-creds
      key: creds