apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: t0services.vj.com
  namespace: crossplane-poc-new
  labels:
    provider: azure
    vnet: crossplane-poc-new
spec:
  compositeTypeRef:
    apiVersion: vj.com/v1alpha1
    kind: Xt0service
  resources:
    - name: crossplane-poc-new
      base:
        apiVersion: azure.crossplane.io/v1alpha3
        kind: ResourceGroup
        spec:
          location: South India
    - name: crossplane-poc-test-south-india-vnet-new
      base:
        apiVersion: network.azure.crossplane.io/v1alpha3
        kind: VirtualNetwork
        spec:
          location: South India
          properties:
            addressSpace:
              addressPrefixes:
                - 10.2.0.0/24