apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositiont0services.vj.com
  labels:
    provider: azure
    vnet: crossplane-poc-new
spec:
  compositeTypeRef:
    apiVersion: vj.com/v1alpha1
    kind: crdt0service
  resources:
    - name: vnet
      base:
        apiVersion: network.azure.crossplane.io/v1alpha3
        kind: VirtualNetwork
        metadata:
          labels:
            provider: azure
            vnet: crossplane-poc-new
        spec:
          resourceGroupNameSelector:
            matchControllerRef: true
            matchLabels:
              provider: azure
              vnet: crossplane-poc-new
          location: South India
          providerConfigRef:
            name: az-provider-config
          properties:
            addressSpace:
              addressPrefixes:
                - 10.2.0.0/24
    - name: resourcegroup
      base:
        apiVersion: azure.crossplane.io/v1alpha3
        kind: ResourceGroup
        metadata:
          labels:
            provider: azure
            vnet: crossplane-poc-new
        spec:
          location: South India
          providerConfigRef:
            name: az-provider-config
    - name: subnet
      base:
        apiVersion: network.azure.crossplane.io/v1alpha3
        kind: Subnet
        metadata:
          labels:
            provider: azure
            vnet: crossplane-poc-new
        spec:
          resourceGroupNameSelector:
            matchControllerRef: true
            matchLabels:
              provider: azure
              vnet: crossplane-poc-new
          virtualNetworkNameSelector:
            matchControllerRef: true
            matchLabels:
              provider: azure
              vnet: crossplane-poc-new
          location: South India
          providerConfigRef:
            name: az-provider-config
          properties:
            addressPrefix: 10.2.0.0/25
    - name: vm
      base:
        apiVersion: compute.azure.jet.crossplane.io/v1alpha1
        kind: LinuxVirtualMachine
        metadata:
          labels:
            provider: azure
            vnet: crossplane-poc-new
        spec:
          providerConfigRef:
            name: az-provider-config
          forProvider:
            adminUserName: azuser
            location: South India
            name: vm
            networkInterfaceIds: ====
            osDisk:
              caching: ReadWrite
              storageAccountType: Standard_LRS
              diskSizeGb: 4
            size: Standard_B1s
          resourceGroupNameSelector:
            matchControllerRef: true
            matchLabels:
              provider: azure
              vnet: crossplane-poc-new
    - name: nic
      base:
        apiVersion: compute.azure.jet.crossplane.io/v1alpha2
        kind: NetworkInterface
        metadata:
          labels:
            provider: azure
            vnet: crossplane-poc-new
        spec:
          providerConfigRef:
            name: az-provider-config
          forProvider:
            ipConfiguration:
              - name: aznic
                privateIpAddressAllocation: Dynamic
                subnetIdselector:
                  matchControllerRef: true
                  matchLabels:
                    provider: azure
                    vnet: crossplane-poc-new                
            location: South India
            name: vm
          resourceGroupNameSelector:
            matchControllerRef: true
            matchLabels:
              provider: azure
              vnet: crossplane-poc-new

          
