apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: crdt0services.vj.com
spec:
  group: vj.com
  names:
    kind: crdt0service
    plural: crdt0services
  claimNames:
    kind: claimt0service
    plural: claimt0services  
  versions:
  - name: v1alpha1
    referenceable: true
    served: true